name: Deploy Flask App to AWS Elastic Beanstalk via CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Setup Node.js (for CDK CLI)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 4️⃣ Install CDK dependencies
      - name: Install CDK dependencies
        working-directory: cdk
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk

      # 5️⃣ Build Flask app zip
      - name: Build Flask app zip
        run: |
          chmod +x build.sh
          ./build.sh

      # 6️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 7️⃣ Upload app.zip to S3 bucket used by CDK
      - name: Upload app.zip to S3
        run: |
          BUCKET_NAME=$(aws s3api list-buckets --query "Buckets[?starts_with(Name, 'flaskappbucket')].Name" --output text)
          aws s3 cp app.zip s3://$BUCKET_NAME/app.zip

      # 8️⃣ Bootstrap and Deploy CDK
      - name: Bootstrap & Deploy CDK
        working-directory: cdk
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ap-south-1
        run: |
          cdk bootstrap aws://$CDK_DEFAULT_ACCOUNT/ap-south-1
          cdk deploy --require-approval never
